### ISSUE TITLE
pval & par NULL values on vignette data

### ISSUE THREAD

**Issue by FlukeBones** [Vivianstats/Phitest#2]
When running Phitest as laid out in the vignette:

>install.packages("PhitestR")
>library(PhitestR)
>library(ggplot2)

>data = readRDS("Example.rds")
>object = data$count
>label = data$labels

>result = phitest(object, label, ncores = 2)
>pval = result$pval

and on our data in the same way, all values given in "result" are "NULL" (e.g. both pval & par). ![Result table](https://user-images.githubusercontent.com/92447150/186126386-f59c556d-fae1-464f-b4f4-7d19120e0309.png)

We have tested this on multiple Windows PCs, using both R 4.3 and R 4.2.1, installing Phitest through CRAN repository and directly via the tar.gz.

**Comment by Vivianstats** [comment]
Hi Luke,

I will look into this and let you know when I find out the reason.

Best,
Vivian

**Comment by Vivianstats** [comment]
Hi Luke,

Is it possible for you to try it again using Mac or Linux platforms? I tested the code again based on R version 4.2.0 and it ran smoothly. Since this package uses the parallel package, which is known to have problems with Windows, it would be helpful if you could see the issues are reproducible on Mac or Linux.

**Comment by FlukeBones** [comment]
Hi Vivian,

I can confirm that the package runs fine on Linux. 

Thanks!
